export const CARD_ADD_REQUEST = 'CARD_ADD_REQUEST'
export const CARD_ADD_SUCCESS = 'CARD_ADD_SUCCESS'
export const CARD_ADD_FAIL = 'CARD_ADD_FAIL'
export const CARD_ADD_RESET = 'CARD_ADD_RESET'

export const CARD_LIST_REQUEST = 'CARD_LIST_REQUEST'
export const CARD_LIST_SUCCESS = 'CARD_LIST_SUCCESS'
export const CARD_LIST_FAIL = 'CARD_LIST_FAIL'