export const PAYMENT_REQUEST = 'PAYMENT_REQUEST'
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'
export const PAYMENT_FAIL = 'PAYMENT_FAIL'
export const PAYMENT_RESET = 'PAYMENT_RESET'

export const REWARD_POINTS_REQUEST = 'REWARD_POINTS_REQUEST'
export const REWARD_POINTS_SUCCESS = 'REWARD_POINTS_SUCCESS'
export const REWARD_POINTS_FAIL = 'REWARD_POINTS_FAIL'