export const REWARD_POINTS_REQUEST = 'REWARD_POINTS_REQUEST';
export const REWARD_POINTS_SUCCESS = 'REWARD_POINTS_SUCCESS';
export const REWARD_POINTS_FAIL = 'REWARD_POINTS_FAIL';

export const ALL_COUPONS_REQUEST = 'ALL_COUPONS_REQUEST';
export const ALL_COUPONS_SUCCESS = 'ALL_COUPONS_SUCCESS';
export const ALL_COUPONS_FAIL = 'ALL_COUPONS_FAIL';
export const ALL_COUPONS_RESET = 'ALL_COUPONS_RESET';
