export const STATEMENT_BY_DATE_REQUEST = 'STATEMENT_BY_DATE_REQUEST'
export const STATEMENT_BY_DATE_SUCCESS = 'STATEMENT_BY_DATE_SUCCESS'
export const STATEMENT_BY_DATE_FAIL = 'STATEMENT_BY_DATE_FAIL'
export const STATEMENT_BY_DATE_RESET = 'STATEMENT_BY_DATE_RESET'