export const STATEMENT_BY_DATE_REQUEST = 'STATEMENT_BY_DATE_REQUEST'
export const STATEMENT_BY_DATE_SUCCESS = 'STATEMENT_BY_DATE_SUCCESS'
export const STATEMENT_BY_DATE_FAIL = 'STATEMENT_BY_DATE_FAIL'
export const STATEMENT_BY_DATE_RESET = 'STATEMENT_BY_DATE_RESET'

export const STATEMENT_RECENT_5_REQUEST = 'STATEMENT_RECENT_5_REQUEST'
export const STATEMENT_RECENT_5_SUCCESS = 'STATEMENT_RECENT_5_SUCCESS'
export const STATEMENT_RECENT_5_FAIL = 'STATEMENT_RECENT_5_FAIL'
export const STATEMENT_RECENT_5_RESET = 'STATEMENT_RECENT_5_RESET'